@startuml
skinparam classAttributeIconSize 0
class Person{
    - name : string
    - firstname : string
    - phonenumber : string
    - emailaddress : string
    - languages : string[]

    + Person(name:string, firstname:string, phonenumber:string, emailaddress:string, languages:string[])
    + <<get>>name():string
    + <<get>>firstname():string
    + <<get>>phonenumber():string
    + <<get, set>>languages():string[]
}

@enduml